#!/usr/bin/env bash

# Train HERE YOU RUN YOUR PROGRAM
# python3 ./test.py --dataset_mode mayo --name baseline_cycleGAN --model cycle_gan --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_baseline_12 --experiment_name baseline_12 --windowing True
# python3 ./train.py --dataset_mode mayo --name baseline_cycleGAN --model cycle_gan --text_file ./data/emph_pretrain.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html  --batch_size 2 --display_id 0 --metric_folder metrics_baseline_12 --experiment_name div_1  --divergence_loss True --lambda_texture 0 --lambda_perceptual 0 --n_epochs 100 --n_epochs_decay 200 --windowing True --emphysema True --window_center -800 --window_width 800
# python3 ./unit_test.py --dataset_mode mayo --name unit --model unit --dataroot False --gpu_ids -1 --input_nc 3 --output_nc 3 --load_size 256 --channels 3 --img_height 256 --img_width 256 --metric_folder metrics_texture_max_diff_1 --experiment_name texture_max_diff_1 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_baseline_diff_1--experiment_name pix2pix_baseline_diff_1 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_baseline_diff_2  --experiment_name pix2pix_baseline_diff_2 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_baseline_diff_3 --experiment_name pix2pix_baseline_diff_3 --windowing True

# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_texture_max_diff0001_1 --experiment_name pix2pix_texture_max_diff0001_1 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_texture_max_diff0001_2 --experiment_name pix2pix_texture_max_diff0001_2 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_texture_max_diff0001_3 --experiment_name pix2pix_texture_max_diff0001_3 --windowing True

# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_texture_avg_diff0001_1  --experiment_name pix2pix_texture_avg_diff0001_1 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_texture_avg_diff0001_2  --experiment_name pix2pix_texture_avg_diff0001_2 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_texture_avg_diff0001_3  --experiment_name pix2pix_texture_avg_diff0001_3  --windowing True

# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_texture_Frob_diff0001_1 --experiment_name pix2pix_texture_Frob_diff0001_1 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_texture_Frob_diff0001_2 --experiment_name pix2pix_texture_Frob_diff0001_2 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_texture_Frob_diff0001_3 --experiment_name pix2pix_texture_Frob_diff0001_3 --windowing True

# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_texture_att_diff0001_1 --experiment_name pix2pix_texture_att_diff0001_1 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_texture_att_diff0001_2 --experiment_name pix2pix_texture_att_diff0001_2 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_texture_att_diff0001_3 --experiment_name pix2pix_texture_att_diff0001_3 --windowing True

# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_perceptual_diff_3 --experiment_name pix2pix_perceptual_diff_3 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_perceptual_diff_4 --experiment_name pix2pix_perceptual_diff_4 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --metric_folder metrics_pix2pix_perceptual_diff_5 --experiment_name pix2pix_perceptual_diff_5--windowing True

# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --experiment_name pix2pix_autoencoder_1 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --experiment_name pix2pix_autoencoder_2 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --experiment_name pix2pix_autoencoder_3 --windowing True

# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --experiment_name pix2pix_ssim_1 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --experiment_name pix2pix_ssim_2 --windowing True
# python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --experiment_name pix2pix_ssim_3 --windowing True

python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --experiment_name pix2pix_edge_1 --windowing True
python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --experiment_name pix2pix_edge_2 --windowing True
python3 ./test.py --dataset_mode mayo --name pix-2-pix_baseline --model pix2pix --text_file ./data/mayo_training_9pat.csv --dataroot False --gpu_ids -1 --load_size 256 --input_nc 1 --output_nc 1 --no_html --display_id 0 --experiment_name pix2pix_edge_3 --windowing True
